name: font_asset_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-276.0.dev

dependencies:
  flutter:
    sdk: flutter
  hooks: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  config:
    enable-dart-data-assets: true
  # fonts:
  #   - family: RobotoMono
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: BBHBartle
  #     fonts: 
  #       - asset: fonts/BBHBartle-Regular.ttf
  #   - family: DancingScript
  #     fonts:
  #     - asset: fonts/dancing_script.ttf
